name: Sync

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@master
        with:
          gitee-username: PeterPan
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: kzcy/kzcy
